#!/usr/bin/env python3
from __future__ import annotations
import argparse,gzip,json,re
from pathlib import Path

def is_cert(p,obj):
 if re.search(r'cert|witness|proof',p.name,re.I):return True
 if isinstance(obj,dict):
  keys=' '.join(map(str,obj.keys())).lower()
  return any(x in keys for x in ('certificate','certificates','witness','counterfactual'))
 return False
def macro(k):return ''.join(x.capitalize() for x in k.split('_'))
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--artifact',type=Path,default=Path(__file__).resolve().parents[1]);ap.add_argument('--output',type=Path);ap.add_argument('--tex-out',type=Path);ns=ap.parse_args();root=ns.artifact.resolve();rows=[]
 for p in sorted(root.rglob('*.json')):
  if any(x in p.parts for x in ('__pycache__','reproduced','docs')):continue
  try:raw=p.read_bytes();obj=json.loads(raw)
  except:continue
  if not is_cert(p,obj):continue
  z=gzip.compress(raw,compresslevel=9,mtime=0)
  if gzip.decompress(z)!=raw:raise AssertionError(p)
  rows.append({'file':p.relative_to(root).as_posix(),'raw_bytes':len(raw),'gzip_bytes':len(z),'ratio':len(z)/len(raw) if raw else 0})
 raw_total=sum(x['raw_bytes'] for x in rows);gz_total=sum(x['gzip_bytes'] for x in rows)
 vals={'file_count':len(rows),'raw_total_bytes':raw_total,'gzip_total_bytes':gz_total,
       'raw_max_bytes':max((x['raw_bytes'] for x in rows),default=0),'gzip_max_bytes':max((x['gzip_bytes'] for x in rows),default=0),
       'aggregate_percent':round(100*gz_total/raw_total,2) if raw_total else 0}
 report={'schema_version':1,**vals,'files':rows,'interpretation':'gzip is evaluated only as a lossless storage/transport wrapper; it does not change certificate semantics or checker complexity.'}
 out=ns.output or root/'results'/'certificate-compression.json';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n')
 md=['# Certificate compression sensitivity','',report['interpretation'],'',f"- Files: {vals['file_count']}",f"- Raw total: {raw_total:,} bytes",f"- gzip total: {gz_total:,} bytes",f"- Raw maximum: {vals['raw_max_bytes']:,} bytes",f"- gzip maximum: {vals['gzip_max_bytes']:,} bytes",f"- Aggregate gzip size: {vals['aggregate_percent']:.2f}% of raw"]
 out.with_suffix('.md').write_text('\n'.join(md)+'\n')
 if ns.tex_out:
  ns.tex_out.parent.mkdir(parents=True,exist_ok=True)
  lines=['% Generated by analyze_certificate_compression.py; do not edit.']
  for k,v in vals.items():
   if isinstance(v,float):sv=f'{v:.2f}'
   elif isinstance(v,int):sv=f'{v:,}'
   else:sv=str(v)
   lines.append(f"\\newcommand{{\\CertComp{macro(k)}}}{{{sv}}}")
  ns.tex_out.write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
