#!/usr/bin/env python3
"""Quantify how META-INF inclusion changes the frozen-frame collision graph."""
from __future__ import annotations
import argparse,json,re,zipfile
from collections import Counter
from pathlib import Path

def canonical(n):
 n=n.replace('\\','/')
 if n.startswith('/') or '\x00' in n:raise ValueError
 ps=n.split('/')
 if any(x in ('','.','..') for x in ps):raise ValueError
 return '/'.join(ps)
def find_frame(root):
 cs=[]
 for d in [root]+[x for x in root.rglob('*') if x.is_dir()]:
  if sum(1 for p in d.rglob('*.jar') if p.is_file())==107:cs.append(d)
 if not cs:raise RuntimeError('107-JAR frame not found')
 return max(cs,key=lambda p:len(p.parts))
def paths(p):
 out=set()
 with zipfile.ZipFile(p) as z:
  for i in z.infolist():
   if i.is_dir():continue
   try:out.add(canonical(i.filename))
   except ValueError:continue
 return out
def cat(n):
 u=n.upper()
 if not u.startswith('META-INF/'):return 'non_metadata'
 if u=='META-INF/MANIFEST.MF':return 'manifest'
 if u.startswith('META-INF/SERVICES/'):return 'services'
 if re.search(r'\.(SF|RSA|DSA|EC)$',u):return 'signature'
 if u.startswith('META-INF/MAVEN/'):return 'maven_metadata'
 if u in {'META-INF/LICENSE','META-INF/LICENSE.TXT','META-INF/NOTICE','META-INF/NOTICE.TXT','META-INF/DEPENDENCIES'}:return 'license_notice'
 return 'other_metadata'
def macro(n):return ''.join(x.capitalize() for x in n.split('_'))
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--artifact',type=Path,default=Path(__file__).resolve().parents[1]);ap.add_argument('--frame',type=Path);ap.add_argument('--output',type=Path);ap.add_argument('--tex-out',type=Path);ap.add_argument('--strict',action='store_true');ns=ap.parse_args()
 root=ns.artifact.resolve();frame=ns.frame.resolve() if ns.frame else find_frame(root/'inputs');jars=sorted(frame.rglob('*.jar'));m={p.relative_to(frame).as_posix():paths(p) for p in jars};keys=sorted(m)
 pair_counts=Counter();entry_occ=Counter();pair_rows=[]
 for i,a in enumerate(keys):
  for b in keys[i+1:]:
   common=m[a]&m[b]
   if not common:continue
   cats=Counter(cat(n) for n in common)
   pair_counts['all_collision_pairs']+=1
   for c in cats:pair_counts[c+'_pairs']+=1
   if cats.get('non_metadata'):pair_counts['non_metadata_collision_pairs']+=1
   else:pair_counts['metadata_only_collision_pairs']+=1
   for n in common:entry_occ[cat(n)]+=1
   pair_rows.append({'a':a,'b':b,'collision_entries':len(common),'categories':dict(sorted(cats.items()))})
 for key in ('all_collision_pairs','non_metadata_collision_pairs','metadata_only_collision_pairs','manifest_pairs','services_pairs','signature_pairs','maven_metadata_pairs','license_notice_pairs','other_metadata_pairs'):
  pair_counts.setdefault(key,0)
 for key in ('non_metadata','manifest','services','signature','maven_metadata','license_notice','other_metadata'):
  entry_occ.setdefault(key,0)
 report={'schema_version':1,'archive_count':len(jars),'unordered_pair_count':len(jars)*(len(jars)-1)//2,
         'pair_counts':dict(sorted(pair_counts.items())),'colliding_entry_occurrences':dict(sorted(entry_occ.items())),
         'pairs':pair_rows,'interpretation':'META-INF categories are reported separately because common build tools apply category-specific transformers; the main uniform first-winner study uses non-metadata entries.'}
 out=ns.output or root/'results'/'metadata-sensitivity.json';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n')
 md=['# Metadata-exclusion sensitivity','',report['interpretation'],'','| Measure | Count |','|---|---:|']
 for k,v in report['pair_counts'].items():md.append(f"| {k.replace('_',' ')} | {v} |")
 md+=['','## Colliding entry occurrences','', '| Category | Pair-entry occurrences |','|---|---:|']+[f"| {k.replace('_',' ')} | {v} |" for k,v in report['colliding_entry_occurrences'].items()]
 out.with_suffix('.md').write_text('\n'.join(md)+'\n')
 if ns.tex_out:
  ns.tex_out.parent.mkdir(parents=True,exist_ok=True)
  vals={'archive_count':len(jars),'unordered_pair_count':report['unordered_pair_count'],**report['pair_counts'],**{k+'_entry_occurrences':v for k,v in entry_occ.items()}}
  lines=['% Generated by artifact/scripts/analyze_metadata_sensitivity.py; do not edit.']
  for k,v in sorted(vals.items()):lines.append(f"\\newcommand{{\\MetaSens{macro(k)}}}{{{v:,}}}")
  ns.tex_out.write_text('\n'.join(lines)+'\n')
 if ns.strict and (len(jars)!=107 or report['unordered_pair_count']!=5671 or pair_counts['non_metadata_collision_pairs']!=40):raise SystemExit('unexpected retained-frame counts')
if __name__=='__main__':main()
